### ISSUE TITLE
插件库和插件管理器规范简述

### ISSUE THREAD

**Issue by zhang-anzhi** [MCDReforged/PluginCatalogue#100]
# 插件仓库

## 概览

向本仓库添加插件, 需要作者长期维护 [mcdreforged.plugin.yml](#mcdreforgedpluginyml),
一次性提交 [plugin_id.yml](#plugin_idyml)

`plugin_id.yml` 中提供插件基本信息, 提供指向 `mcdreforged.plugin.yml` 的链接

`mcdreforged.plugin.yml` 包括版本历史、下载地址、依赖包、依赖插件等信息, 插件管理器依据本文件安装插件

### 一个例子

小明开发了一个新插件 `pl`, 在 GitHub开源, 想要加入插件库

小明需要 fork 本仓库, 向本仓库的 `meta` 文件夹中添加 `pl.yml`, 内容如下:

```yaml
id: pl
name: Pl
author: xiaoming
describe:
  en_us: My plugin
  zh_cn: 我的插件
link: https://github.com/xiaoming/pl
info_link: https://raw.githubusercontent.com/xiaoming/pl/master/mcdreforged.plugin.yml
```

小明在他的开源仓库增加一个 `mcdreforged.plugin.yml` 文件, 同时给 0.0.1 版本的提交打一个名为 `0.0.1` 的 tag, 内容如下:

```yaml
id: pl
name: Pl
author: xiaoming
describe:
  en_us: My plugin
  zh_cn: 我的插件
link: https://github.com/xiaoming/pl
version:
  0.0.1:
    files:
      pl.py: https://raw.githubusercontent.com/xiaoming/pl/0.0.1/pl.py
```

当小明更新插件时, 同步给 `mcdreforged.plugin.yml` 的 version 添加以下内容:

```yaml
0.0.2:
    files:
      pl.py: https://raw.githubusercontent.com/xiaoming/pl/0.0.2/pl.py
```

更新后的 `mcdreforged.plugin.yml` 是这样的:

```yaml
id: pl
name: Pl
author: xiaoming
describe:
  en_us: My plugin
  zh_cn: 我的插件
link: https://github.com/xiaoming/pl
version:
  0.0.1:
    files:
      pl.py: https://raw.githubusercontent.com/xiaoming/pl/0.0.1/pl.py
  0.0.2:
    files:
      pl.py: https://raw.githubusercontent.com/xiaoming/pl/0.0.2/pl.py
```

更新 commit 之后, 给这次提交打一个tag `0.0.2`

如果小明的插件有依赖或安装脚本, 详见 [mcdreforged.plugin.yml](#mcdreforgedpluginyml)

## 本仓库简介

本仓库有以下文件, 除 `plugin_id.yml` 手动添加外均由 `github actions` 自动生成：

| 文件名 | 位置 | 作用 |
| - | - | - |
| [plugin_id.yml](#plugin_idyml) | meta/ | 增加新插件时作者提供的插件信息 |
| [plugin_id.md](#plugin_idmd) | docs/lang/catalogue/ |单个插件描述 |
| index.md | docs/lang/ | 完整插件目录 |
| full.md | docs/lang/ | 完整插件描述 |
| [plugin_list.json](#plugin_listjson) | / | 插件列表 |

本仓库文件结构：

```text
meta/
    plugin_id.yml
    ...
docs/
    en_us/
        catalogue/
            plugin_id.md
            ...
        index.md
        full.md
    zh_cn/
        ...
scripts/
    ...
plugin_list.json
readme.md
```

### plugin_id.yml

```yaml
id: str（插件id）
name: str（插件名)
author: str/array（作者）
describe:
  en_us: str（英文介绍）
  zh_cn: str（中文介绍）
link: str（展示地址，可以是repo）
info_link: str（指向插件信息mcdreforged.plugin.yml的链接）
```

### plugin_id.md

```markdown
# name

> describe

ID: id
Authors: authors
Link: [name](link)

```

### plugin_list.json

由 GitHub actions 自动生成的完整插件列表

```json
{
  "data": [
    {
      "id": "",
      "name": "",
      "author": "",
      "describe": {
        "en_us": "",
        "zh_cn": ""
      },
      "link": "",
      "info_link": ""
    }
  ],
  "update_at": 0
}
```

## 添加插件到本仓库

作者需维护一个名为 `mcdreforged.plugin.yml` 的文件, 存储位置任意, 获取到该文件的链接

向本仓库添加 `plugin_id.yml`, 参考 [plugin_id.yml](#plugin_idyml)

### mcdreforged.plugin.yml

```yaml
id: str（插件id）
name: str（插件名)
author: str/array（作者）
describe:
  en_us: str（英文介绍）
  zh_cn: str（中文介绍）
link: str（展示地址，可以是repo）
setup: str（安装脚本链接，可选）
dependencies（依赖，可选）:
  python（python依赖）:
    requests: '*'
    PyYAML: '5.4.1'
  plugin（插件依赖）:
    minecraft_data_api: '*'
    vault: '>=0.0.1'
version:
  0.0.1:
    files（所有文件按此结构下载到plugins中）:
      plugin.py: str（链接）
      plugin（文件夹名）:
        tool.py: str（链接）
    setup: str（安装脚本链接，python可执行文件，可选）
    dependencies（依赖，可选）:
      python: object（python依赖）
      plugin: object（插件依赖）
  0.0.2:
    ...
  ...
```

#### setup

插件的安装脚本链接, 为 `.py` 文件, 插件管理器直接执行一遍该脚本

脚本执行路径: `MCDR 工作路径`

可以为每个版本单独指定

#### dependencies

插件的依赖, 分为 python 包依赖和插件依赖

可以为每个版本单独指定

## 插件管理器安装插件步骤

- 读取 `plugin_list.json` 并找到插件
- 根据 `info_link` 找到并读取 `mcdreforged.plugin.yml`
- 根据指定版本将 `files` 中的文件下载到 `plugins` 文件夹中
- 下载并执行 `setup` 指定的安装脚本
- 安装 `dependencies` 中的 python 包
- 重复以上步骤直到 `dependencies` 中的 `plugin` 安装完成

## 优点

1. 插件版本历史等信息在作者可以随时维护的 `mcdreforged.plugin.yml` 中, 便于作者更新
2. 插件下载考虑到单文件和多文件情况, 可以在 `files` 中填写多个文件来进行下载
3. 提供 `setup` 字段, 作者可以利用按照脚本进行个性化配置; 也可以用于在 `files` 中填写一个压缩包链接, 由安装脚本处理
4. 可以针对不同版本指定 `setup` 和 `dependencies`
5. 该方案在涉及其他链接和文件的地方选择使用 `文件直链` 的方式, 所以稳定性十分优秀, 而且可以去与 git 的耦合
6. 可以由社区来帮助一些作者维护 `mcdreforged.plugin.yml`

## 缺点

1. 插件库可以镜像, 但是下载插件无法镜像, 只能依靠作者在 `mcdreforged.plugin.yml` 给的链接
